apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: elog-authentication-build
  name: elog-authentication-build
  namespace: elog-authentication-service
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'elog-authentication:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker