kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "marketplace-authentication-pipeline"
spec:
  source:
    git:
      ref: main
      uri: 'https://github.com/Maxis-System-Limited/marketplace-authentication-service'
    sourceSecret:
      name: marketplace-authentication-secret
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/jenkinsFile
    type: JenkinsPipeline