apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: marketplace-authentication
  name: marketplace-authentication
  namespace: marketplace-authentication-service
spec:
  host: marketplace-authentication-maxis.nagadpay.com 
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: marketplace-authentication
    weight: 100
  wildcardPolicy: None